name = "pharmx-social"
compatibility_date = "2024-08-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# Build configuration
[build]
command = "npm run build"

# Pages Functions configuration (if needed)
# [pages_functions]
# directory = "functions"
