name = "pharmx-social"
pages_build_output_dir = "out"
compatibility_date = "2024-08-21"

# Environment variables for the frontend
[vars]
NEXT_PUBLIC_API_URL = "https://pharmx-api.kasimhussain333.workers.dev/api/v1"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"
