name = "pharmx-social"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "YOUR_DATABASE_ID" # You'll get this after creating the D1 database
