name = "pharmx-social"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npx @cloudflare/next-on-pages@1"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"
