name = "pharmx-worker-api"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Production environment configuration
[env.production]
vars = { 
  MAX_CONCURRENT_CALLS = "50",
  MAX_QUEUE_SIZE = "200", 
  MAX_CONNECTIONS_PER_ROOM = "10",
  CALL_TIMEOUT_SECONDS = "1200",
  QUEUE_TIMEOUT_MS = "300000",
  RATE_LIMIT_WINDOW_MS = "900000",
  RATE_LIMIT_MAX_REQUESTS = "5"
}

# Development environment configuration  
[env.development]
vars = { 
  MAX_CONCURRENT_CALLS = "10",
  MAX_QUEUE_SIZE = "50",
  MAX_CONNECTIONS_PER_ROOM = "5", 
  CALL_TIMEOUT_SECONDS = "600",
  QUEUE_TIMEOUT_MS = "180000",
  RATE_LIMIT_WINDOW_MS = "900000",
  RATE_LIMIT_MAX_REQUESTS = "10"
}

# Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"

# Object storage binding
[[r2_buckets]]
binding = "AVATAR_STORAGE"
bucket_name = "pharmx-avatars"

# Key-value storage binding for sessions and caching
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Durable Object bindings
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"  
class_name = "MatchmakingQueue"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

# Production Durable Object memory limits
[env.production.durable_objects]
memory_limit = "128"

# Analytics binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Database migrations
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "MatchmakingQueue", "LobbyDO"]

# Cron triggers for cleanup and maintenance
[triggers]
crons = ["0 2 * * *"]

# Note: The following secrets should be set via `wrangler secret put`:
# JWT_SECRET - Required for JWT token signing
# GOOGLE_CLIENT_ID - Google OAuth client ID
# GOOGLE_CLIENT_SECRET - Google OAuth client secret  
# GOOGLE_REDIRECT_URI - OAuth redirect URI
# FRONTEND_URL - Frontend application URL for OAuth redirects
