name = "pharmx-api-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Basic configuration - we'll add environment-specific vars later

# Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"

# Object storage binding
[[r2_buckets]]
binding = "AVATAR_STORAGE"
bucket_name = "pharmx-avatars"

# Key-value storage binding for sessions and caching
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Durable Object bindings
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"  
class_name = "MatchmakingQueue"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

# Basic Durable Object configuration

# Analytics binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Database migrations
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "MatchmakingQueue", "LobbyDO"]

# Cron triggers for cleanup and maintenance
[triggers]
crons = ["0 2 * * *"]

# Note: The following secrets should be set via `wrangler secret put`:
# JWT_SECRET - Required for JWT token signing
# GOOGLE_CLIENT_ID - Google OAuth client ID
# GOOGLE_CLIENT_SECRET - Google OAuth client secret  
# GOOGLE_REDIRECT_URI - OAuth redirect URI
# FRONTEND_URL - Frontend application URL for OAuth redirects
