name = "pharmx-api"
main = "src/index.ts"
compatibility_date = "2024-08-21"

# Worker configuration
[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database binding (using the same database as before)
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"

# KV namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "1140c2d4954340bd8bf15960f3b9df45"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"
class_name = "MatchmakingQueue"

[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

# Migrations for Durable Objects (using SQLite for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchmakingQueue", "ChatRoom"]
