name = "pharmx-api-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Basic configuration - we'll add environment-specific vars later

# Durable Object bindings (required for the worker to deploy)
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"  
class_name = "MatchmakingQueue"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

# Static asset configuration (use assets binding for Worker static content)
assets = { directory = "./public", binding = "ASSETS" }

# Routes to serve the app on custom domain
routes = [
  { pattern = "chat.pharmx.co.uk/*", zone_name = "pharmx.co.uk" }
]

# Durable Object migrations (required for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom", "MatchmakingQueue", "LobbyDO"]

# Cron triggers for cleanup and maintenance
[triggers]
crons = ["0 2 * * *"]

# Note: The following secrets should be set via `wrangler secret put`:
# JWT_SECRET - Required for JWT token signing
# GOOGLE_CLIENT_ID - Google OAuth client ID
# GOOGLE_CLIENT_SECRET - Google OAuth client secret  
# GOOGLE_REDIRECT_URI - OAuth redirect URI
# FRONTEND_URL - Frontend application URL for OAuth redirects
