name = "pharmx-api"
main = "src/index.ts"
compatibility_date = "2024-08-21"

# Environment variables
[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://chat.pharmx.co.uk"

# NOTE: The following environment variables MUST be set as secrets:
# wrangler secret put AUTH0_DOMAIN
# wrangler secret put AUTH0_CLIENT_ID  
# wrangler secret put AUTH0_CLIENT_SECRET
# wrangler secret put JWT_SECRET
# wrangler secret put AUTH0_ISSUER_BASE_URL
# wrangler secret put AUTH0_REDIRECT_URI

# Worker configuration
[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database binding (using the same database as before)
[[d1_databases]]
binding = "DB"
database_name = "pharmx-social-db"
database_id = "9050344e-9b99-4651-a0cc-a5eaeed7c39d"

# KV namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "1140c2d4954340bd8bf15960f3b9df45"

# R2 bucket for avatar storage
[[r2_buckets]]
binding = "AVATARS"
bucket_name = "pharmx-avatars"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"
class_name = "MatchmakingQueue"

[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

# Migrations for Durable Objects (using SQLite for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchmakingQueue", "ChatRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LobbyDO"]

# NOTE: The following environment variables need to be set as secrets:
# wrangler secret put JWT_SECRET
# wrangler secret put AUTH0_CLIENT_SECRET
# wrangler secret put TURN_USERNAME (optional)
# wrangler secret put TURN_CREDENTIAL (optional)
