name = "pharmx-voice-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "MatchmakerDO"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["MatchmakerDO", "RoomDO"]
